# TravisCI (https://travis-ci.org) configuration file
# https://docs.travis-ci.com/user/languages/python

language: python
arch : 
 - ppc64le
 - amd64
# ensures that we have UUID filesystem mounts for proper testing
sudo: true
dist: trusty

addons:
  # add localhost to known_hosts to prevent ssh unknown host prompt during unit tests
  ssh_known_hosts: localhost

python:
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

before_install:
  # disable mongodb as we don't need it and it sometimes temporary fails
  # https://github.com/travis-ci/travis-ci/issues/4937#issuecomment-149289729
  - sudo rm -f /etc/apt/sources.list.d/mongodb.list
  - sudo apt-get -qq update
  # install screen, and util-linux (provides flock) for test_sshtools
  - sudo apt-get install -y sshfs screen util-linux

install:
  - pip install coveralls
  # add ssh public / private key pair to ensure user can start ssh session to localhost for tests
  - ssh-keygen -b 2048 -t rsa -f /home/travis/.ssh/id_rsa -N ""
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  # start ssh-agent so that we can add private keys
  - eval `ssh-agent -s`

script:
  # compile all files - ensure that syntax is correct
  - python -m compileall common common/test common/plugins qt qt/plugins
  # run unit tests - ensure that functionality is correct
  - cd common && ./configure && make unittest-v

after_success:
  - coverage combine
  - coveralls
